abo-abo/lispy

lispy-test.el, lispy.el
This fixes an issue where <kbd>M-k</kbd> would leave a dangling double-quote in the buffer when issuing `lispy-kill-sentence` from the opening double-quote.  :point_up_2:
=> Fix `lispy-kill-sentence` when on boundary of string

lispy.el
Curious about your opinion on this...
I use `lispy-back` all the time, but it falls over sometimes when you're rearranging things in your buffer, hit <kbd>bbbb</kbd> a few times and end up somewhere else inserting a bunch of `b` characters because the point you're returning to is no longer special because it was originally saved from a position that *was* special.
This amends `lispy-back` to skip over positions that aren't special.  There's still the possibility of you ending up in a place you never were, but at least you shouldn't end up inserting.
Is there a better way to handle this?
=> Adjust `lispy-back' to always return to special positions

lispy.el
Not comprehensive at all, just some cases I came across most often. `defn` should be take-2 not take-3 if you consider defn with multi-arity:
```
(defn foo
([x] (bar x))
([x y]
(if (predicate? x)
(bar x)
(baz x))))
```
Further, for defn with docstrings take-2 is preferable.
```
;; good
(defn foo
"docstring"
[x]
(bar x))
;; bad
(defn foo "docstring"
[x]
(bar x))
```
=> Add more basic multiline cases for Clojure

lispy.el
The overlay will stay active for one second, then hide.
This depends on cider 0.10, which is not yet released. At the moment this is only available in the cider development snapshot. I tried to be careful and take this into account.
Also it should be noted that in cider, the user is allowed to configure overlays on or off. When overlays are off, cider will display a `(message)` with the result instead. The default configuration is to show both the overlay and a `(message)`.
=> Show overlay when evaluating a clojure expression interactively

lispy-test.el
Tests attached.
(The test syntax is awesome. I hope I got it right!)
=> Fix lispy-splitting of Clojure literals

lispy-test.el, lispy.el
This patch fixes spacing after indentation for Clojure unquoting and unquote-splicing.
After indentation:
```clojure
`(1 2 ~ (expr) ~ 'expr '~ (expr) ~ '(expr) ~@ (expr))
```
After indentation (applying patch):
```clojure
`(1 2 ~(expr) ~'expr '~(expr) ~'(expr) ~@(expr))
```
I'm just now familiarizing myself with lispy, so while the above patch seems to work, I'm not sure if there is a better place to fix the issue.
=> Fix indentation for Clojure unquoting.

lispy.el
When swapping "a" and "h" in the default setup (ca6634fc), one example
in the commentary wasn't changed.
=> Fix documentation

lispy-tags.el
If running in a terminal, fringe-mode is not available. Check if
fringe-mode is bound in lispy--format-tag-line to make it usable if
running in a terminal.
=> Check if fringe-mode is bound.

lispy-test.el, lispy.el
`(lispy-slurp -1)` will slurp past the current line when before a multi-line list instead of doing nothing. I was relying on this behavior for #240 and realized that this wasn't documented correctly.
=> Improve lispy-slurp docstring

le-lisp.el
This prevents the error in the case that SLY or SLIME hasn't yet been started.
=> Ensure SLIME or SLY is running in lispy-goto-symbol-lisp

.gitignore
This is just a few additions to the `.gitignore` file.
=> Ignore cask, elc, backup, and lock files

lispy.el
This PR try to fix indent for @(...) and #?(...).
__@(...)__
There're common usages for @() in Clojure:
```clojure
(do
@(d/transact conn xxx))
```
The indent should not separate the `@` and the following parentheses. 
__#?@(...)__
This is the reader conditional splice syntax.
=> fix indent for @(...) and #?@(...)

lispy.el
Add variable lispy-delete-backward-recenter to customize this. Any
number means call recenter with that arg when point is at top of screen
and calling lispy-delete-backward. Value of nil means don't recenter.
Any critiques or better ideas welcome :)
=> Only recenter on lispy-delete when desired

lispy-test.el, lispy.el
This fixes a bug for the safe actions where right quotes weren't considered unmatched if `lispy-safe-actions-ignore-strings` was non-nil and they were at the end of the region.
=> Prevent unmatched right quotes from being deleted

lispy-pkg.el
I haven't tested this completely, but the tests do pass:
Ran 133 tests, 133 results as expected (2016-04-26 11:05:20-0500)
I prefer to just use melpa-stable. The only version of iedit available in melpa-stable is 0.9.9. Based on the release histories, https://github.com/tsdh/iedit/releases and https://github.com/victorhge/iedit/releases, it would seem as though 0.97 is pretty out-of-date. I'm not certain 0.97 came from tsdh/iedit. It does seem like the new "official" repository is victorhge/iedit as that's what melpa points to: http://melpa.org/#/iedit.
=> Bump iedit to latest stable version v0.9.9.

lispy-test.el, lispy.el
This addresses the `lispy-pair` part of #245.
The regex may need to be tweaked a little. For example, looking at the previous space-unless regex for `lispy-parens`, I'm not sure for which lisp `_` or `%` can come before `(`. I'm also not sure what the left side of `\\(?:> \\|#\\?\\)` is supposed to check for.
On a side note, what are you using as `lisp-indent-function`? Some places are indented as with `common-lisp-indent-function` (the `defalias`s), but elsewhere it seems `lisp-indent-function` is used (the `defface`s). Which should I be using for lispy?
=> Add variables for valid delimiter-preceding syntax

lispy.el
#287 Added clojurescript-mode to above alists, and also replaced
conditionals that explicitly looked for 'clojure-mode to use
lispy-clojure-modes
=> Adding clojurescript to *-preceding-syntax-alists

lispy.el
`yank-pop` refuses to work unless it thinks the previous command was
`yank`, so set `this-command` appropriately.
=> Ensure we can call yank-pop after lispy-yank.

lispy.el
Since `lispy-space` isn't bound with `lispy-define-key`, `eldoc-add-command` is never called on it.
=> Allow eldoc to work after lispy-space

Makefile, index.html, index.org, parinfer_index.html, parinfer_index.org
This addresses #229 and #230. There are currently two formatting problems that I am not sure how to fix.
The first is that the links are underlined in `parinfer_index.html`. The second is that having `|` before `"` in a source block breaks how it is displayed (see `case 3` under the last function heading `lispy-delete-or-splice-or-slurp`).
=> Add documentation for parinfer functions

lispy.el
The previous version did not work when scroll-margin>0, and called from
top-level of form repeatedle. All tests pass, do you see anything wrong with
this?
=> Fix lispy-view when scroll-margin >0

lispy-test.el, lispy.el
This fixes an issue where safe deletion, for example, would delete an unmatched delimiter just before a comment (brought up in noctuid/lispyville#8).
=> Minor fix to lispy--find-unmatched-delimiters

lispy.el
Otherwise, pressing DEL (calling lispy-delete-backward) does nothing
when we have an active, empty region.
This is particularly common when using multiple-cursors. Previously,
DEL did nothing when multiple-cursors was active.
=> Ignore empty regions in lispy-delete-backward

lispy.el
God-mode comes in both a global and a local version. At the moment Lispy only works with god-global-mode. This is a trivial change to make it work with god-local-mode as well.
=> Make Lispy work with god-local-mode.

README.md
Escape | (marking cursor) in table so that table formats correctly.
=> Fix lispy-clone table

lispy.el
Hello !
This would make the life of some of us easier :) In CL (at least) it is common practice to type a `lib:symbol` and thus the regexp (AFAIUnderstood) does not make much sense.
fixes #380
=> new lispy-colon-p to disable the insertion of a space before a colon

lispy.el
- Use case is for typing a vector literal in Common Lisp
such as `#(1 2 3)`
=> Cannot go to nil, and bounds dwim can produce nil if in front of a hash

lispy.el
When results contain %, an error "not enough arguments for format string" would be issued. This should escape the % in result and fix the problem.
=> lispy-eval-outline: replace % with %% in results

lispy.el
This just allows wrapping more than one sexp with `lispy-wrap-round`, `lispy-wrap-braces`, and `lispy-wrap-brackets`.
I noticed that `lispy-pair` will not actually wrap when in a string. This makes only makes sense for the autowrap commands. If the user explicitly gives an argument or uses `lispy-wrap-round`, I think it should always wrap. Would it be okay for me to change `lispy-pair` allow for this?
Also related, would it be okay for me to add a variable like this to allow `(` to insert `()` in strings?
```
(if (and lispy-parens-only-left-in-string ; defaults to t to preserve current behavior
(string= ,left "(")
(= ?\( (aref (this-command-keys-vector) 0)))
(insert "(")
(insert ,left ,right)
(backward-char 1))
```
=> Support prefix arguments for lispy-wrap-round etc.

lispy.el
=> Declare lispy-delete-atom-from-within obsolete

lispy.el
Fixes #436 
Also added a space to docstring to avoid opening delimiter on left margin.
=> Add advice for undo-tree-undo

le-clojure.el
- I prefer to `cider-connect` into a running CIDER REPL
=> Make the method of creating/connecting to CIDER configurable

lispy.el
For example character constants `?\;` or scheme sexp comments `#;`
=> Don't comment after `\` or `#`

README.md, lispy-test.el, lispy.el
Hi Oleh,
This adds a new last-threading toggle command and associated functions.  This is something I do a lot, so having a command to quickly toggle between the forms is useful.  It seems to work well.  I added tests for some common forms, and documentation in what seem to be the right places.
Note that in a separate commit I also added a debug declaration to the `lispy-from-left` macro, which I used while debugging this new code.
Hopefully this will be acceptable, but please let me know if you would like any changes to be made.
Thanks for your work on this package.
=> Thread last

lispy.el
undo-tree-undo takes an optional variable ARG, but lispy--undo-tree-advice
actually requires it. Make the argument optional.
=> Make lispy--undo-tree-advice have proper signature

lispy.el
I don't use cider and I'd rather not have to install it just to get the overlay. I already use eros, which was extracted from cider just for the overlay. Would it be okay to support both?
Thanks!
=> Support eros for overlay

lispy.el
This prevents the extra space (which breaks valid janet code) during auto format
=> Add a couple extra parse lines for janet 

lispy.el
Currently, with `(add-hook 'eval-expression-minibuffer-setup-hook #'lispy-mode)`, if you eval something while using edebug, pressing `e` again will call `edebug-eval-expression` again instead of self inserting.
=> Fix edebug-eval-expression when using lispy in minibuffer

lispy.el
Hi there,
When I'm investigating a function, I like to narrow the buffer to it to make it easier to focus on it.  However, when I'm in an `edebug` session, I find it easier to clone the buffer, and narrow to that function in that cloned buffer.  It makes it easier to visit other functions in the file.
`lispy-isolate` is a proof-of-concept that does just that.  The name's not great, but before going forward, I'd prefer to make sure that you haven't already implemented something similar.  If not, I'd be willing to write something a little more fleshed out.
=> Implement lispy-isolate

lispy.el
=> Fix a typo.

lispy.el
`lispy-eval-alist` seemingly points to the wrong evaluation function for racket-mode.
The function `lispy-eval-racket` (used currently) expects 0 arguments, while the proposed `lispy--eval-racket` (both already existing in `le-racket.el`) expects a string to evaluate.
This causes an error when trying to evaluate sexps in racket-mode using lispy, raising the error `Wrong number of arguments: (0 . 0), 1`.
=> Updates eval-alist to use correct function for racket
